name: Build
description: Build ruby image
inputs:
  version:
    description: version
    required: true
  dev:
    description: dev version of image
    required: false
  user_id:
    description: user id
    required: false
  group_id:
    description: group id
    required: false
  tags:
    description: image tags
    required: true
  platform:
    description: os arch
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      RUBY_VER: ${{ inputs.version }}
      RUBY_DEV: ${{ inputs.dev }}
      WODBY_USER_ID: ${{ inputs.user_id }}
      WODBY_GROUP_ID: ${{ inputs.group_id }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
